# DIABOLO

In [2]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
#from  pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)

import pandas as pd
import numpy as np



#vous pouvez modifier cette option à votre guise
pd.options.display.max_rows = 10

                   
Location_csv = 'd:\diabolo.csv'
xnames=['ALLURE','DATE_COURSE','CO_DISTANCE','CO_NB','CO_PRIX','HIPPO','IDCOURSE','IDPARTCIPANT','PAR_age','PAR_ARRIVE',
'PAR_CARRIERE','PAR_CARRIERE_Q','PAR_CLASSE_AGE','PAR_CORDE','PAR_COTEDER','PAR_ENT_ECART_GAGNANT','PAR_ENT_RAPPORT_GAGNANT_M',
'PAR_ENT_RAPPORT_GANGANT','PAR_ENT_REU_PLACE','PAR_ENT_REUSSITE_GAGNE','PAR_ENT_VICTOIRE','PAR_GAIN','pAR_JOC_ECART_GAGNANT',
'PAR_JOC_ECART_PLACE','PAR_JOC_NB_COURSE','PAR_JOC_PLACE_3P','pAR_JOC_RAPPORT_GAGNANT_M','PAR_JOC_REU_PLACE','pAR_JOC_REUSSITE_GAGNE',
'pAR_JOC_VICTOIRE','PAR_NP','PAR_NUM','PAR_PLACE','PAR_PLACE_Q','PAR_REUSSITE_3P','PAR_REUSSITE_GAGNE','PAR_REUSSITE_QUINTE','PAR_RUESSITE_PLACE','autostart','cendre','grande_piste','sable_fibre','dirt','FIN_ligne']
    
df=pd.read_csv (Location_csv, sep=';',names=xnames,nrows=10000,skipinitialspace=True,encoding='Latin-1')

df=df.groupby('ALLURE')     
df=df.get_group(1) 

#Suppression de la collone TROT
df.drop(["ALLURE"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["FIN_ligne"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["DATE_COURSE"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["IDPARTCIPANT"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["HIPPO"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["IDCOURSE"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["PAR_CORDE"], axis=1, inplace=True)

#xnames=['CO_DISTANCE','CO_NB','CO_PRIX','HIPPO','IDCOURSE','PAR_age','PAR_ARRIVE',
#'PAR_CARRIERE','PAR_CARRIERE_Q','PAR_CLASSE_AGE','PAR_CORDE','PAR_COTEDER','PAR_ENT_ECART_GAGNANT','PAR_ENT_RAPPORT_GAGNANT_M',
#'PAR_ENT_RAPPORT_GANGANT','PAR_ENT_REU_PLACE','PAR_ENT_REUSSITE_GAGNE','PAR_ENT_VICTOIRE','PAR_GAIN','pAR_JOC_ECART_GAGNANT',
#'PAR_JOC_ECART_PLACE','PAR_JOC_NB_COURSE','PAR_JOC_PLACE_3P','pAR_JOC_RAPPORT_GAGNANT_M','PAR_JOC_REU_PLACE','pAR_JOC_REUSSITE_GAGNE',
#'pAR_JOC_VICTOIRE','PAR_NP','PAR_PLACE','PAR_PLACE_Q','PAR_REUSSITE_3P','PAR_REUSSITE_GAGNE','PAR_REUSSITE_QUINTE','PAR_RUESSITE_PLACE','autostart','cendre','grande_piste','sable_fibre','dirt']
   
#Transformer une colonne en un index dans un dataframe
#df = df.set_index('IDPARTCIPANT')

#affichage des premiere lignes du jeu de données
df.head()

,CO_DISTANCE,CO_NB,CO_PRIX,PAR_age,PAR_ARRIVE,PAR_CARRIERE,PAR_CARRIERE_Q,PAR_CLASSE_AGE,PAR_COTEDER,PAR_ENT_ECART_GAGNANT,...,PAR_PLACE_Q,PAR_REUSSITE_3P,PAR_REUSSITE_GAGNE,PAR_REUSSITE_QUINTE,PAR_RUESSITE_PLACE,autostart,cendre,grande_piste,sable_fibre,dirt
9,0,17,90000,5,99,41,5,44456,32,6,...,0,0.292683,0.121951,0.00000,0.170732,1,1,1,0,0
10,0,17,90000,6,4,58,3,34229,8,41,...,2,0.396552,0.155172,0.00000,0.241379,1,1,1,0,0
11,0,17,90000,6,2,41,9,40630,36,0,...,4,0.585366,0.317073,0.04878,0.268293,1,1,1,0,0
12,0,17,90000,6,1,64,2,39671,6,0,...,0,0.500000,0.218750,0.03125,0.281250,1,1,1,0,0
13,0,17,90000,5,99,10,1,48270,10,0,...,0,0.800000,0.600000,0.00000,0.200000,1,1,1,0,0

In [3]:
# trvail sur les courses de trot (allure=1)
print(df.shape)

(5473, 37)

In [5]:
#enumeration des colonnes
df.columns

Index(['CO_DISTANCE', 'CO_NB', 'CO_PRIX', 'PAR_age', 'PAR_ARRIVE',
       'PAR_CARRIERE', 'PAR_CARRIERE_Q', 'PAR_CLASSE_AGE', 'PAR_COTEDER',
       'PAR_ENT_ECART_GAGNANT', 'PAR_ENT_RAPPORT_GAGNANT_M',
       'PAR_ENT_RAPPORT_GANGANT', 'PAR_ENT_REU_PLACE',
       'PAR_ENT_REUSSITE_GAGNE', 'PAR_ENT_VICTOIRE', 'PAR_GAIN',
       'pAR_JOC_ECART_GAGNANT', 'PAR_JOC_ECART_PLACE', 'PAR_JOC_NB_COURSE',
       'PAR_JOC_PLACE_3P', 'pAR_JOC_RAPPORT_GAGNANT_M', 'PAR_JOC_REU_PLACE',
       'pAR_JOC_REUSSITE_GAGNE', 'pAR_JOC_VICTOIRE', 'PAR_NP', 'PAR_NUM',
       'PAR_PLACE', 'PAR_PLACE_Q', 'PAR_REUSSITE_3P', 'PAR_REUSSITE_GAGNE',
       'PAR_REUSSITE_QUINTE', 'PAR_RUESSITE_PLACE', 'autostart', 'cendre',
       'grande_piste', 'sable_fibre', 'dirt'],
      dtype='object')

In [6]:
#gagnant
#sélection des chevaux dans les 5 premiers


df_gagnant = df

In [7]:
df_gagnant=df_gagnant[df_gagnant.PAR_GAIN >0]
df_gagnant

,CO_DISTANCE,CO_NB,CO_PRIX,PAR_age,PAR_ARRIVE,PAR_CARRIERE,PAR_CARRIERE_Q,PAR_CLASSE_AGE,PAR_COTEDER,PAR_ENT_ECART_GAGNANT,...,PAR_PLACE_Q,PAR_REUSSITE_3P,PAR_REUSSITE_GAGNE,PAR_REUSSITE_QUINTE,PAR_RUESSITE_PLACE,autostart,cendre,grande_piste,sable_fibre,dirt
9,0,17,90000,5,99,41,5,44456,32,6,...,0,0.292683,0.121951,0.00000,0.170732,1,1,1,0,0
10,0,17,90000,6,4,58,3,34229,8,41,...,2,0.396552,0.155172,0.00000,0.241379,1,1,1,0,0
11,0,17,90000,6,2,41,9,40630,36,0,...,4,0.585366,0.317073,0.04878,0.268293,1,1,1,0,0
12,0,17,90000,6,1,64,2,39671,6,0,...,0,0.500000,0.218750,0.03125,0.281250,1,1,1,0,0
13,0,17,90000,5,99,10,1,48270,10,0,...,0,0.800000,0.600000,0.00000,0.200000,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,14,17000,4,99,10,0,27,0,21,...,0,0.000000,0.000000,0.00000,0.000000,1,0,0,0,0
9996,0,14,17000,4,99,49,0,1492,7,47,...,0,0.244898,0.102041,0.00000,0.142857,1,0,0,0,0
9997,0,14,17000,4,4,33,0,1915,173,5,...,0,0.151515,0.030303,0.00000,0.121212,1,0,0,0,0
9998,0,14,17000,4,99,22,0,2110,28,36,...,0,0.227273,0.000000,0.00000,0.227273,1,0,0,0,0
9999,0,16,21000,8,5,90,1,12887,8,0,...,0,0.277778,0.122222,0.00000,0.155556,1,0,0,0,0

In [8]:
import numpy as np

len(df_gagnant)

UneSerie = pd.Series(df_gagnant['PAR_ARRIVE'])                       # Une DATAFRAME est composée de serie

#Suppression de la collone TROT
df_gagnant.drop(["PAR_ARRIVE"], axis=1, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [9]:
#df_gagnant = df_gagnant.frame(df_gagnant,UneSerie)
df_gagnant['PAR_ARRIVE'] = UneSerie
print(df_gagnant)

      CO_DISTANCE  CO_NB  CO_PRIX  PAR_age  PAR_CARRIERE  PAR_CARRIERE_Q  \
9               0     17    90000        5            41               5
10              0     17    90000        6            58               3
11              0     17    90000        6            41               9
12              0     17    90000        6            64               2
13              0     17    90000        5            10               1
...           ...    ...      ...      ...           ...             ...
9995            0     14    17000        4            10               0
9996            0     14    17000        4            49               0
9997            0     14    17000        4            33               0
9998            0     14    17000        4            22               0
9999            0     16    21000        8            90               1

      PAR_CLASSE_AGE  PAR_COTEDER  PAR_ENT_ECART_GAGNANT  \
9              44456           32                      6
10             34229            8                     41
11             40630           36                      0
12             39671            6                      0
13             48270           10                      0
...              ...          ...                    ...
9995              27            0                     21
9996            1492            7                     47
9997            1915          173                      5
9998            2110           28                     36
9999           12887            8                      0

      PAR_ENT_RAPPORT_GAGNANT_M     ...      PAR_REUSSITE_3P  \
9                          8.96     ...             0.292683
10                         6.85     ...             0.396552
11                         8.72     ...             0.585366
12                         0.00     ...             0.500000
13                         3.33     ...             0.800000
...                         ...     ...                  ...
9995                      10.40     ...             0.000000
9996                      17.35     ...             0.244898
9997                      18.10     ...             0.151515
9998                      15.48     ...             0.227273
9999                       0.00     ...             0.277778

      PAR_REUSSITE_GAGNE  PAR_REUSSITE_QUINTE  PAR_RUESSITE_PLACE  autostart  \
9               0.121951              0.00000            0.170732          1
10              0.155172              0.00000            0.241379          1
11              0.317073              0.04878            0.268293          1
12              0.218750              0.03125            0.281250          1
13              0.600000              0.00000            0.200000          1
...                  ...                  ...                 ...        ...
9995            0.000000              0.00000            0.000000          1
9996            0.102041              0.00000            0.142857          1
9997            0.030303              0.00000            0.121212          1
9998            0.000000              0.00000            0.227273          1
9999            0.122222              0.00000            0.155556          1

      cendre  grande_piste  sable_fibre  dirt  PAR_ARRIVE
9          1             1            0     0          99
10         1             1            0     0           4
11         1             1            0     0           2
12         1             1            0     0           1
13         1             1            0     0          99
...      ...           ...          ...   ...         ...
9995       0             0            0     0          99
9996       0             0            0     0          99
9997       0             0            0     0           4
9998       0             0            0     0          99
9999       0             0            0     0           5

[4444 rows x 37 columns]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [10]:
df_gagnant.columns

Index(['CO_DISTANCE', 'CO_NB', 'CO_PRIX', 'PAR_age', 'PAR_CARRIERE',
       'PAR_CARRIERE_Q', 'PAR_CLASSE_AGE', 'PAR_COTEDER',
       'PAR_ENT_ECART_GAGNANT', 'PAR_ENT_RAPPORT_GAGNANT_M',
       'PAR_ENT_RAPPORT_GANGANT', 'PAR_ENT_REU_PLACE',
       'PAR_ENT_REUSSITE_GAGNE', 'PAR_ENT_VICTOIRE', 'PAR_GAIN',
       'pAR_JOC_ECART_GAGNANT', 'PAR_JOC_ECART_PLACE', 'PAR_JOC_NB_COURSE',
       'PAR_JOC_PLACE_3P', 'pAR_JOC_RAPPORT_GAGNANT_M', 'PAR_JOC_REU_PLACE',
       'pAR_JOC_REUSSITE_GAGNE', 'pAR_JOC_VICTOIRE', 'PAR_NP', 'PAR_NUM',
       'PAR_PLACE', 'PAR_PLACE_Q', 'PAR_REUSSITE_3P', 'PAR_REUSSITE_GAGNE',
       'PAR_REUSSITE_QUINTE', 'PAR_RUESSITE_PLACE', 'autostart', 'cendre',
       'grande_piste', 'sable_fibre', 'dirt', 'PAR_ARRIVE'],
      dtype='object')

In [11]:
df_gagnant.dtypes

CO_DISTANCE     int64
CO_NB           int64
CO_PRIX         int64
PAR_age         int64
PAR_CARRIERE    int64
                ...
cendre          int64
grande_piste    int64
sable_fibre     int64
dirt            int64
PAR_ARRIVE      int64
Length: 37, dtype: object

In [12]:
#transformation en matrice numpy - seul reconnu par scikit-learn
 Find the min and max values for each column

In [35]:
#X matrice des var. explicatives
X = data[:,0:35]
print(X)
#y vecteur de la var. à prédire
y = data[:,36]

[[  0.00000000e+00   1.70000000e+01   9.00000000e+04 ...,   1.00000000e+00
    1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.70000000e+01   9.00000000e+04 ...,   1.00000000e+00
    1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.70000000e+01   9.00000000e+04 ...,   1.00000000e+00
    1.00000000e+00   0.00000000e+00]
 ...,
 [  0.00000000e+00   1.40000000e+01   1.70000000e+04 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.40000000e+01   1.70000000e+04 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.60000000e+01   2.10000000e+04 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]]

In [78]:
#utilisation du module model_selection de scikit-learn (sklearn)
from sklearn import model_selection
from sklearn import linear_model, datasets

#subdivision des données – éch.test = 300 ; éch.app = 768 – éch.test = 468
X_app,X_test,y_app,y_test = model_selection.train_test_split(X,y,test_size = 500)
print(X_app.shape,X_test.shape,y_app.shape,y_test.shape)

(3944, 35) (500, 35) (3944,) (500,)

In [79]:
#exécution de l'instance sur les données d'apprentissage
#c.à-d. construction du modèle prédictif
modele = lr.fit(X_app,y_app)

In [80]:
# Robustly fit linear model with RANSAC algorithm
ransac = linear_model.RANSACRegressor()