In [106]:
allure_etudier=1

In [107]:
import  sys

#LOCALISATION DES DONNEES
sys.path.insert(0, "C:/projets_python/diabolo")

import warnings
warnings.filterwarnings("ignore")



#LIBRAIRIES PERSO
import etude_variable.MyLog as log
#import etude_variable.jouer as jouer

#import etude_variable.analyse as ana

# LIBRAIRIE PYHTON CLASSIQUES
import pandas as pd

import numpy as np
import matplotlib
import scipy
import platform

from collections import Counter

#ESTIMATEUR
import sklearn
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.ensemble import  RandomForestClassifier
from sklearn import neighbors, datasets
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Imputer

from sklearn.ensemble import GradientBoostingClassifier

#MISE A l ECHELLE
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import quantile_transform

from scipy.stats import uniform
from scipy.stats import randint

#TRAINING
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from skopt import BayesSearchCV
import dask_searchcv as dcv
from skopt.space import Real, Integer
from sklearn.model_selection import cross_validate

#Evaluateur
from sklearn.model_selection import KFold

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

from sklearn.feature_selection import SelectFromModel


from evolutionary_search import EvolutionaryAlgorithmSearchCV
from sklearn.utils import class_weight

#outils
from dask.diagnostics import ProgressBar
import logging
from datetime import datetime


#Metriques
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import learning_curve
from sklearn import  metrics
from sklearn.metrics import  roc_auc_score
from sklearn.metrics import  classification_report

#Outils

import time


#Graphique
from matplotlib import pyplot
from matplotlib import pyplot as plt
import seaborn as sns

print('Operating system version....', platform.platform())
print("Python version is........... %s.%s.%s" % sys.version_info[:3])
print('scikit-learn version is.....', sklearn.__version__)
print('pandas version is...........', pd.__version__)
print('numpy version is............', np.__version__)
print('matplotlib version is.......', matplotlib.__version__)
print('scipy version is.......', scipy.__version__)

Operating system version.... Windows-10-10.0.17134-SP0
Python version is........... 3.6.5
scikit-learn version is..... 0.19.1
pandas version is........... 0.22.0
numpy version is............ 1.14.2
matplotlib version is....... 2.2.0
scipy version is....... 1.0.0

# LECTURE DES DONNEES

In [108]:
# Creating bins for the win column
def assign_selection(W):
    if W <=2:
        return 1
    else:
        return 0
    
    # Creating bins for the win column
def assign_selection2(W):
    if W == 1.0:
        return 1
    if W == 0.0:
        return 0
    
def my_drop(df, col):
    if col in df:
        df.drop([col], axis=1, inplace=True)
    return df
    


def transformation(df2,allure_etudier):
    #Filtre des données¶
    print('\n\n----------- TRANSFORMATION --------- AJOUT DE COLONNE------------\n')
    start_time=timer()
    #df2=df2[df2.Point>0]
    df2 = df2[df2.PAR_COTEDER > 0]
    df2 = df2[df2.CO_PRIX > 0]
    df2 = df2[df2.PAR_ARRIVE > 0]  # On garde la ligne qui possede information arrivée
    df2 = df2.groupby("ALLURE")
    df2 = df2.get_group(allure_etudier)
    df2 = my_drop(df2, 'ALLURE')

    if allure_etudier == 2 or allure_etudier == 4 or allure_etudier == 5:
        df2 = df2[df2.POIDS > 20]
        df2 = df2[df2.POIDS < 80]
    #  on a lu les données avant l 'ajout de la colonne SELECTIOB
    df2['SELECTION2'] = df2['PAR_ARRIVE'].apply(assign_selection)
    df2 = my_drop(df2, 'PAR_ARRIVE')
  
    timer(start_time)
    return df2

In [109]:
def lecture_data(Fichier, xnames, xindex_col, allure=1, mode_debug=0, avec_index=True):
    
    print("DATA ....")
    start_time=timer()
    if avec_index==True:
        df = pd.read_csv(Fichier,  index_col=xindex_col,     sep=';',     names=xnames,               skipinitialspace=True,              encoding='Latin-1')
    else:
        df = pd.read_csv(Fichier,   index_col=None,  sep=';',                     names=xnames,                         skipinitialspace=True,     encoding='Latin-1')

    df = df.groupby("ALLURE")
    df = df.get_group(allure)
    #print(df.info())

    print(timer(start_time))
    return df

In [110]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        print(start_time)
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

# fit speciaux

In [111]:
  # Lecture des données sans index
xnames = ['ALLURE', 'CO_DISTANCE',
              'CO_PRIX', 'HIPPO',
              'IDCOURSE', 'IDPARTCIPANT',
              'PAR_AGE', 'PAR_ARRIVE',
              'PAR_CARRIERE',
              'PAR_CARRIERE_Q',
              'PAR_CLASSE_AGE',
              'PAR_COTEDER',
              'PAR_ENT_ECART_GAGNANT',
              'PAR_ENT_RAPPORT_GAGNANT_M',
              'PAR_ENT_REU_PLACE',
              'PAR_ENT_REUSSITE_GAGNE',
              'PAR_ENT_VICTOIRE',
              'PAR_GAIN',
              'pAR_JOC_ECART_GAGNANT',
              'PAR_JOC_ECART_PLACE',
              'PAR_JOC_NB_COURSE',
              'PAR_JOC_PLACE_3P',
              'pAR_JOC_RAPPORT_GAGNANT_M',
              'PAR_JOC_REU_PLACE',
              'pAR_JOC_REUSSITE_GAGNE',
              'pAR_JOC_VICTOIRE',
              'PAR_NP',
              'PAR_NUM',
              'PAR_PLACE',
              'PAR_PLACE_Q',
              'PAR_REUSSITE_3P',
              'PAR_REUSSITE_GAGNE',
              'PAR_REUSSITE_QUINTE',
              'PAR_RUESSITE_PLACE',
              'autostart',
              'cendre',
              'grande_piste',
              'Point',
              'Nb_partant',
              'PAR_PROPRIO',
              'NOM_JOC',
              'NOM_ENTR',
              'POIDS',
              'CORDE', 'CHEVAL',
              'MUSIC_CHEVAL',
              'MUSIC_ENT',
              'MUSIC_JOC',
              'PAR_VALEUR',
              'PAR_ENT_ECART_PLACE',
              'PAR_VICTOIRE',
              'PAR_VICTOIRE_Q',
          'PAR_ENT_NB_COURSE',
              'FIN_ligne']

In [112]:
def nettoyer_Nan(df):
    df[['PAR_ENT_ECART_GAGNANT']] = df[['PAR_ENT_ECART_GAGNANT']].fillna( df[['PAR_ENT_ECART_GAGNANT']].mean())
    df[['PAR_ENT_RAPPORT_GAGNANT_M']] = df[['PAR_ENT_RAPPORT_GAGNANT_M']].fillna( df[['PAR_ENT_RAPPORT_GAGNANT_M']].mean())
    df[['PAR_ENT_REU_PLACE']] = df[['PAR_ENT_REU_PLACE']].fillna( df[['PAR_ENT_REU_PLACE']].mean())
    df[['PAR_ENT_REUSSITE_GAGNE']] = df[['PAR_ENT_REUSSITE_GAGNE']].fillna( df[['PAR_ENT_REUSSITE_GAGNE']].mean())
    df[['PAR_ENT_VICTOIRE']] = df[['PAR_ENT_VICTOIRE']].fillna( df[['PAR_ENT_VICTOIRE']].mean())
    df[['PAR_ENT_NB_COURSE']] = df[['PAR_ENT_NB_COURSE']].fillna( df[['PAR_ENT_NB_COURSE']].mean())
    
    df[['pAR_JOC_ECART_GAGNANT']] = df[['pAR_JOC_ECART_GAGNANT']].fillna( df[['pAR_JOC_ECART_GAGNANT']].mean())
    df[['pAR_JOC_RAPPORT_GAGNANT_M']] = df[['pAR_JOC_RAPPORT_GAGNANT_M']].fillna( df[['pAR_JOC_RAPPORT_GAGNANT_M']].mean())
    df[['PAR_JOC_REU_PLACE']] = df[['PAR_JOC_REU_PLACE']].fillna( df[['PAR_JOC_REU_PLACE']].mean())
    df[['pAR_JOC_REUSSITE_GAGNE']] = df[['pAR_JOC_REUSSITE_GAGNE']].fillna( df[['pAR_JOC_REUSSITE_GAGNE']].mean())
    df[['pAR_JOC_VICTOIRE']] = df[['pAR_JOC_VICTOIRE']].fillna( df[['pAR_JOC_VICTOIRE']].mean())
    df[['PAR_JOC_ECART_PLACE']] = df[['PAR_JOC_ECART_PLACE']].fillna( df[['PAR_JOC_ECART_PLACE']].mean())
    df[['PAR_JOC_NB_COURSE']] = df[['PAR_JOC_NB_COURSE']].fillna( df[['PAR_JOC_NB_COURSE']].mean())
    df[['PAR_JOC_PLACE_3P']] = df[['PAR_JOC_PLACE_3P']].fillna( df[['PAR_JOC_PLACE_3P']].mean())
    df['PAR_RUESSITE_PLACE'] = df['PAR_RUESSITE_PLACE'].fillna( df['PAR_RUESSITE_PLACE'].mean())
    df[['PAR_REUSSITE_GAGNE']] = df[['PAR_REUSSITE_GAGNE']].fillna( 0)
    df[['PAR_REUSSITE_3P']] = df[['PAR_REUSSITE_3P']].fillna( df[['PAR_REUSSITE_3P']].mean())
    df[['PAR_CARRIERE']] = df[['PAR_CARRIERE']].fillna( df[['PAR_CARRIERE']].mean())
    df[['PAR_CARRIERE_Q']] = df[['PAR_CARRIERE_Q']].fillna( df[['PAR_CARRIERE_Q']].mean())
    df[['PAR_GAIN']] = df[['PAR_GAIN']].fillna( df[['PAR_GAIN']].mean())    
    df[['PAR_PLACE']] = df[['PAR_PLACE']].fillna( df[['PAR_PLACE']].mean())
    df[['PAR_PLACE_Q']] = df[['PAR_PLACE_Q']].fillna( df[['PAR_PLACE_Q']].mean())
    df[['PAR_CLASSE_AGE']] = df[['PAR_CLASSE_AGE']].fillna( df[['PAR_CLASSE_AGE']].mean())
        
    return df

In [121]:
index_col = ['IDCOURSE','IDPARTCIPANT']
start_time=timer()
df = lecture_data('d:\data_diabolo.csv', xnames, xindex_col=index_col, allure=allure_etudier, avec_index=False)
df2=df.copy()
#df.set_index("IDPARTCIPANT", inplace=True)
df=transformation(df,allure_etudier)
df=nettoyer_Nan(df)
print(timer(start_time))

2018-06-28 07:03:57.430890
DATA ....
2018-06-28 07:03:57.430890

 Time taken: 0 hours 0 minutes and 2.42 seconds.
None


----------- TRANSFORMATION --------- AJOUT DE COLONNE------------

2018-06-28 07:03:59.904254

 Time taken: 0 hours 0 minutes and 0.48 seconds.

 Time taken: 0 hours 0 minutes and 3.09 seconds.
None

In [122]:
df

,CO_DISTANCE,CO_PRIX,HIPPO,IDCOURSE,IDPARTCIPANT,PAR_AGE,PAR_CARRIERE,PAR_CARRIERE_Q,PAR_CLASSE_AGE,PAR_COTEDER,...,MUSIC_CHEVAL,MUSIC_ENT,MUSIC_JOC,PAR_VALEUR,PAR_ENT_ECART_PLACE,PAR_VICTOIRE,PAR_VICTOIRE_Q,PAR_ENT_NB_COURSE,FIN_ligne,SELECTION2
13,2,52000,1,1616,19849,6,41,1,36220,7,...,NaN,DADA2A1A,5MDA0M3A,0,2,7,1,808,FINFIN,0
14,2,52000,1,1616,19848,7,61,9,30670,199,...,NaN,5A3A7A6A,3A7A7A2A,0,1,5,0,192,FINFIN,0
15,2,52000,1,1616,19847,8,83,9,26118,60,...,NaN,DMDA0A4M,7A1ADADA,0,4,11,1,119,FINFIN,0
16,2,52000,1,1616,19846,6,45,0,33798,3,...,NaN,3A2M3A3A,4ADA2ADA,0,0,10,0,175,FINFIN,1
17,2,52000,1,1616,19845,7,64,4,27212,35,...,NaN,DADA2ADA,DADA2ADA,0,2,9,0,280,FINFIN,1
18,2,52000,1,1616,19844,6,44,2,30805,52,...,NaN,7ADA0M0A,DM3A6M0A,0,6,3,1,79,FINFIN,0
19,2,52000,1,1616,19843,8,56,3,21903,22,...,NaN,7A5A7A2M,DA0A1A0A,0,3,5,0,260,FINFIN,0
20,2,52000,1,1616,19842,6,42,3,26006,12,...,NaN,7A5A7A2M,2A0M1A1A,0,3,6,0,260,FINFIN,0
21,1,52000,1,1616,19841,7,37,1,16302,8,...,NaN,DA7M7A7A,DA3ADA2A,0,5,9,1,162,FINFIN,0
22,1,52000,1,1616,19840,8,63,1,14001,82,...,NaN,DA7ADA7A,1ADA3ADA,0,4,11,0,126,FINFIN,0
23,1,52000,1,1616,19839,8,76,0,13997,60,...,NaN,5A3A4A0A,1ADA2ADA,0,1,4,0,79,FINFIN,0
24,1,52000,1,1616,19838,7,50,0,15805,60,...,NaN,1A2A0A1A,1A0A$0A1,0,0,9,0,5,FINFIN,0
25,1,52000,1,1616,19837,7,30,1,15748,7,...,NaN,2ADA0A3A,2ADA0A3A,0,0,9,0,377,FINFIN,0
26,1,52000,1,1616,19836,8,77,0,13770,136,...,NaN,AM6M6MDM,DMDA1M7M,0,0,6,0,24,FINFIN,0
27,1,52000,1,1616,19835,7,86,1,15684,104,...,NaN,DMDA7A3A,DA5A3ADA,0,3,4,0,93,FINFIN,0
28,1,52000,1,1616,19834,6,39,1,18243,3,...,NaN,4MDA7ADA,2A0ADM7M,0,5,5,1,47,FINFIN,0
29,1,52000,1,1616,19833,7,30,0,15418,199,...,NaN,DA7A7A2M,2ADA7A0A,0,3,5,0,107,FINFIN,0
30,1,52000,1,1616,19832,7,81,1,15404,369,...,NaN,6A0A7A0A,7A4A7A$D,0,23,6,0,147,FINFIN,0
31,1,38000,1,1617,19861,4,11,0,9482,4,...,NaN,2A7A4A7A,2A0A0M7A,0,0,2,0,51,FINFIN,0
32,1,38000,1,1617,19860,4,16,0,9272,7,...,NaN,1ADA7M6A,DADA0A6A,0,0,2,0,667,FINFIN,0
33,1,38000,1,1617,19859,4,13,0,9097,6,...,NaN,DM2M4ADM,7ADADA3A,0,1,1,0,77,FINFIN,0
34,1,38000,1,1617,19858,4,13,0,9040,34,...,NaN,DA1A0ADA,DADA0ADA,0,1,3,0,132,FINFIN,0
35,1,38000,1,1617,19857,4,11,0,8887,6,...,NaN,DA5A7A3M,DA0A1A0A,0,3,1,0,145,FINFIN,0
36,1,38000,1,1617,19856,4,24,0,8772,18,...,NaN,DADM4A5A,2ADMDM0A,0,12,2,0,272,FINFIN,0
37,1,38000,1,1617,19855,4,19,0,8357,7,...,NaN,4A1A7A3A,1A3A6A3A,0,1,1,0,107,FINFIN,0
38,1,38000,1,1617,19854,4,18,0,8345,34,...,NaN,7A5ADA7A,DA3ADA2A,0,12,1,0,73,FINFIN,1
39,1,38000,1,1617,19853,4,12,0,8080,8,...,NaN,DA4A$1A5,4ADADA3A,0,2,2,0,5,FINFIN,1
40,1,38000,1,1617,19852,4,11,0,7247,18,...,NaN,5A0A7A7A,5A0ADA5A,0,4,1,0,393,FINFIN,0
41,1,38000,1,1617,19851,4,15,0,5680,24,...,NaN,2A1A2ADA,3A7A7A2A,0,0,1,0,165,FINFIN,0
42,1,38000,1,1617,19850,4,12,0,4702,14,...,NaN,3M3ADA6M,1A2A7A7A,0,0,0,0,39,FINFIN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490263,1,24000,35,56524,699200,7,81,0,17360,12,...,2A6A0A$,7A0MDA0A,0A0A7A$1,0,5,7,0,107,FINFIN,0
490264,1,24000,35,56524,699201,7,93,2,17608,13,...,4A7A2A7A,4A0A3A0A,4A6A0AAA,0,2,8,0,89,FINFIN,0
490265,1,15000,35,56525,699202,4,53,0,20,16,...,$6A,3A0ADADA,DAAA5A0A,0,0,2,0,35,FINFIN,0
490266,1,15000,35,56525,699203,4,24,0,450,11,...,1A1A4ADA,3ADA2A5A,$7A4A2AD,0,0,3,0,8,FINFIN,0
490267,1,15000,35,56525,699204,4,23,0,455,3,...,3A,7A0MDA0A,0A0A7A$1,0,5,1,0,107,FINFIN,1
490268,1,15000,35,56525,699205,4,14,0,595,6,...,DADADADA,0,3A7A2A1A,0,0,1,0,0,FINFIN,1
490269,1,15000,35,56525,699206,4,10,0,750,51,...,2ADA$DA,0,0,0,0,0,0,0,FINFIN,0
490270,1,15000,35,56525,699207,4,24,0,815,71,...,7ARA$7A,$7A,$7A,0,0,0,0,1,FINFIN,0
490271,1,15000,35,56525,699208,4,27,0,1225,71,...,5A7ARADA,$0A0A0A5,$0A0A,0,0,0,0,5,FINFIN,0
490272,1,15000,35,56525,699209,4,15,0,1322,20,...,7A7A4A$,3A3A1ADA,1A3A0A$3,0,0,0,0,38,FINFIN,0
490273,1,15000,35,56525,699210,4,40,0,1372,7,...,7A3A2A0A,DA7A2M3M,DA4A7ADA,0,2,0,0,83,FINFIN,0
490274,1,15000,35,56525,699211,4,24,0,1400,12,...,0A7A$AA,0A6A3ADA,DM0A0A2A,0,2,1,0,68,FINFIN,0
490275,1,15000,35,56525,699212,4,5,0,1462,10,...,1ADA,6A2A3A1A,7A4ADA7A,0,1,1,0,141,FINFIN,0
490276,1,15000,35,56525,699213,4,17,0,1505,8,...,5A0A$0A,$7M0A0AD,$7M0A0A0,0,0,0,0,5,FINFIN,0
490277,1,15000,35,56525,699214,4,41,0,1605,16,...,7ADA3A$,7M7MDM5M,$4A1A7A6,0,24,0,0,69,FINFIN,0
490278,1,15000,35,56525,699215,4,43,0,1675,9,...,7M7M$7M,$2A4ADAD,0A7M0A2A,0,0,1,0,24,FINFIN,0
490279,1,5000,35,56526,699216,6,39,0,4308,22,...,7A6A7A7A,7A0A$4A7,$0A7A5A7,0,14,1,0,27,FINFIN,0
490280,1,5000,35,56526,699217,7,57,0,4570,10,...,2A7ARA2A,$7A7A2A3,$6A7A,0,2,2,0,39,FINFIN,0
490282,1,5000,35,56526,699219,6,99,0,5550,5,...,2A6A2A0A,2A7ADADA,DADA$2A3,0,0,6,0,30,FINFIN,1
490283,1,5000,35,56526,699220,6,93,0,5848,33,...,6M7A5A$,DM7A7A0M,$DA1A0A5,0,5,2,0,108,FINFIN,0
490284,1,5000,35,56526,699221,6,57,0,5953,5,...,5M2A7A3A,4A0A5ADA,1A0A6A0A,0,30,2,0,85,FINFIN,0
490285,1,5000,35,56526,699222,6,65,0,5960,15,...,DADA3ADA,$0ADA7A6,$0ADA7A6,0,0,1,0,9,FINFIN,0
490286,1,5000,35,56526,699223,6,94,0,6076,8,...,DA3ADA4A,$5A1ADA3,0,0,1,4,0,51,FINFIN,1
490287,2,5000,35,56526,699224,7,94,0,8022,41,...,4A7A4A7A,$0A1A7A3,$0A,0,1,2,0,6,FINFIN,0
490288,2,5000,35,56526,699225,7,96,0,8135,22,...,DA0A3A5A,$DM3M,$7A7A,0,1,2,0,2,FINFIN,0
490289,2,5000,35,56526,699226,7,74,0,8868,54,...,7A7A7A5A,0A7A$4A7,$7A0A,0,0,5,0,10,FINFIN,0
490290,2,5000,35,56526,699227,8,52,0,7802,5,...,3ADA0A7A,DA1ADADA,$1ADA7AD,0,1,6,0,282,FINFIN,0
490292,2,5000,35,56526,699229,8,72,0,8186,16,...,6A6A6A7A,7A1ADA7A,6A$0ADA7,0,1,5,0,8,FINFIN,0
490293,2,5000,35,56526,699230,6,52,0,11070,6,...,2A$7ADA,7A1ADA7A,$7ADA,0,1,2,0,8,FINFIN,0
490294,2,5000,35,56526,699231,7,92,0,9861,14,...,7A0A0A3A,4A0A5ADA,DA6ADA0A,0,30,4,0,85,FINFIN,0

In [125]:
import math
def relation_1(a,b):
    if b==0:
        return 0
    else:
        return (a/b)*20
    
#---------------------------------------------------------------------------------------------------------------------

    
#---------------------------------------------------------------------------------------------------------------------    
def calcul_note(df, num_course, cri):
    valeur_critere=df.loc[df['IDCOURSE']==num_course,cri]  # selection critere    
    maxx=valeur_critere.max() #MAXI
    if ((maxx[0])>0):
        df.loc[df['IDCOURSE']==num_course,cri]  = ((df.loc[df['IDCOURSE']==num_course,cri])/maxx[0])*20
    else:
        df.loc[df['IDCOURSE']==num_course,cri]=0
    
    
    #print(   df.loc[df['IDCOURSE']==num_course,cri] )
    
        

    return  df

In [126]:
i=0
start_time=timer()
for n  in df.groupby(['IDCOURSE'],axis=0):
    nc=n[0]
    if math.fmod(i,1000)==0 or i<20:
        print("    print(N° ",i,timer(start_time))
    #df= calcul_note(df, nc, ['PAR_CARRIERE'] )
    df= calcul_note(df, nc, ['PAR_ENT_ECART_GAGNANT'] )
    df= calcul_note(df, nc, ['PAR_ENT_RAPPORT_GAGNANT_M'] )
    df= calcul_note(df, nc, ['PAR_ENT_REU_PLACE'] )
    df= calcul_note(df, nc, ['PAR_ENT_REUSSITE_GAGNE'] )
    df= calcul_note(df, nc, ['PAR_ENT_VICTOIRE'] ) 
    df= calcul_note(df, nc, ['PAR_ENT_NB_COURSE'] )   
    
    df= calcul_note(df, nc, ['pAR_JOC_ECART_GAGNANT'] )
    df= calcul_note(df, nc, ['pAR_JOC_RAPPORT_GAGNANT_M'] )
    df= calcul_note(df, nc, ['PAR_JOC_REU_PLACE'] )
    
    df= calcul_note(df, nc, ['pAR_JOC_REUSSITE_GAGNE'] )
    df= calcul_note(df, nc, ['pAR_JOC_VICTOIRE'] )    
    df= calcul_note(df, nc, ['PAR_JOC_ECART_PLACE'] )
    df= calcul_note(df, nc, ['PAR_JOC_NB_COURSE'] )    
    
    df= calcul_note(df, nc, ['PAR_JOC_PLACE_3P'] )    
    
    df= calcul_note(df, nc, ['PAR_REUSSITE_GAGNE'] )
    df= calcul_note(df, nc, ['PAR_RUESSITE_PLACE'] )
    df= calcul_note(df, nc, ['PAR_REUSSITE_3P'] )    
    df= calcul_note(df, nc, ['PAR_CARRIERE'] )
    df= calcul_note(df, nc, ['PAR_CARRIERE_Q'] )
    df= calcul_note(df, nc, ['PAR_GAIN'] )
    df= calcul_note(df, nc, ['PAR_PLACE'] )
    df= calcul_note(df, nc, ['PAR_PLACE_Q'] )
    df= calcul_note(df, nc, ['PAR_CLASSE_AGE'] )
    
    
    #df= calcul_note(df, nc, ['POIDS'] )              
    i=i+1

2018-06-28 07:04:34.340568

 Time taken: 0 hours 0 minutes and 0.07 seconds.
    print(N°  0 None

 Time taken: 0 hours 0 minutes and 0.85 seconds.
    print(N°  1 None

 Time taken: 0 hours 0 minutes and 1.06 seconds.
    print(N°  2 None

 Time taken: 0 hours 0 minutes and 1.23 seconds.
    print(N°  3 None

 Time taken: 0 hours 0 minutes and 1.4 seconds.
    print(N°  4 None

 Time taken: 0 hours 0 minutes and 1.56 seconds.
    print(N°  5 None

 Time taken: 0 hours 0 minutes and 1.72 seconds.
    print(N°  6 None

 Time taken: 0 hours 0 minutes and 1.87 seconds.
    print(N°  7 None

 Time taken: 0 hours 0 minutes and 2.03 seconds.
    print(N°  8 None

 Time taken: 0 hours 0 minutes and 2.18 seconds.
    print(N°  9 None

 Time taken: 0 hours 0 minutes and 2.34 seconds.
    print(N°  10 None

 Time taken: 0 hours 0 minutes and 2.49 seconds.
    print(N°  11 None

 Time taken: 0 hours 0 minutes and 2.64 seconds.
    print(N°  12 None

 Time taken: 0 hours 0 minutes and 2.81 seconds.
    print(N°  13 None

 Time taken: 0 hours 0 minutes and 2.97 seconds.
    print(N°  14 None

 Time taken: 0 hours 0 minutes and 3.12 seconds.
    print(N°  15 None

 Time taken: 0 hours 0 minutes and 3.28 seconds.
    print(N°  16 None

 Time taken: 0 hours 0 minutes and 3.43 seconds.
    print(N°  17 None

 Time taken: 0 hours 0 minutes and 3.59 seconds.
    print(N°  18 None

 Time taken: 0 hours 0 minutes and 3.74 seconds.
    print(N°  19 None

 Time taken: 0 hours 1 minutes and 17.3 seconds.
    print(N°  500 None

 Time taken: 0 hours 2 minutes and 33.77 seconds.
    print(N°  1000 None

 Time taken: 0 hours 3 minutes and 50.37 seconds.
    print(N°  1500 None

 Time taken: 0 hours 5 minutes and 6.52 seconds.
    print(N°  2000 None

 Time taken: 0 hours 6 minutes and 22.88 seconds.
    print(N°  2500 None

 Time taken: 0 hours 7 minutes and 39.13 seconds.
    print(N°  3000 None

 Time taken: 0 hours 8 minutes and 56.17 seconds.
    print(N°  3500 None

 Time taken: 0 hours 10 minutes and 13.64 seconds.
    print(N°  4000 None

 Time taken: 0 hours 11 minutes and 31.27 seconds.
    print(N°  4500 None

 Time taken: 0 hours 12 minutes and 48.23 seconds.
    print(N°  5000 None

 Time taken: 0 hours 14 minutes and 5.57 seconds.
    print(N°  5500 None

 Time taken: 0 hours 15 minutes and 21.61 seconds.
    print(N°  6000 None

 Time taken: 0 hours 16 minutes and 37.64 seconds.
    print(N°  6500 None

 Time taken: 0 hours 17 minutes and 53.79 seconds.
    print(N°  7000 None

 Time taken: 0 hours 19 minutes and 10.1 seconds.
    print(N°  7500 None

 Time taken: 0 hours 20 minutes and 26.01 seconds.
    print(N°  8000 None

 Time taken: 0 hours 21 minutes and 41.98 seconds.
    print(N°  8500 None

 Time taken: 0 hours 22 minutes and 57.96 seconds.
    print(N°  9000 None

 Time taken: 0 hours 24 minutes and 14.38 seconds.
    print(N°  9500 None

 Time taken: 0 hours 25 minutes and 30.78 seconds.
    print(N°  10000 None

 Time taken: 0 hours 26 minutes and 47.14 seconds.
    print(N°  10500 None

 Time taken: 0 hours 28 minutes and 3.67 seconds.
    print(N°  11000 None

 Time taken: 0 hours 29 minutes and 20.25 seconds.
    print(N°  11500 None

 Time taken: 0 hours 30 minutes and 36.28 seconds.
    print(N°  12000 None

 Time taken: 0 hours 31 minutes and 52.24 seconds.
    print(N°  12500 None

 Time taken: 0 hours 33 minutes and 8.11 seconds.
    print(N°  13000 None

 Time taken: 0 hours 34 minutes and 24.28 seconds.
    print(N°  13500 None

 Time taken: 0 hours 35 minutes and 40.17 seconds.
    print(N°  14000 None

 Time taken: 0 hours 36 minutes and 55.88 seconds.
    print(N°  14500 None

 Time taken: 0 hours 38 minutes and 12.11 seconds.
    print(N°  15000 None

 Time taken: 0 hours 39 minutes and 28.79 seconds.
    print(N°  15500 None

 Time taken: 0 hours 40 minutes and 45.02 seconds.
    print(N°  16000 None

 Time taken: 0 hours 42 minutes and 1.34 seconds.
    print(N°  16500 None

 Time taken: 0 hours 43 minutes and 17.81 seconds.
    print(N°  17000 None

 Time taken: 0 hours 44 minutes and 34.84 seconds.
    print(N°  17500 None

 Time taken: 0 hours 45 minutes and 51.47 seconds.
    print(N°  18000 None

In [127]:
df

,CO_DISTANCE,CO_PRIX,HIPPO,IDCOURSE,IDPARTCIPANT,PAR_AGE,PAR_CARRIERE,PAR_CARRIERE_Q,PAR_CLASSE_AGE,PAR_COTEDER,...,MUSIC_CHEVAL,MUSIC_ENT,MUSIC_JOC,PAR_VALEUR,PAR_ENT_ECART_PLACE,PAR_VICTOIRE,PAR_VICTOIRE_Q,PAR_ENT_NB_COURSE,FIN_ligne,SELECTION2
13,2,52000,1,1616,19849,6,9.534884,2.222222,36220,7,...,NaN,DADA2A1A,5MDA0M3A,0,2,7,1,808,FINFIN,0
14,2,52000,1,1616,19848,7,14.186047,20.000000,30670,199,...,NaN,5A3A7A6A,3A7A7A2A,0,1,5,0,192,FINFIN,0
15,2,52000,1,1616,19847,8,19.302326,20.000000,26118,60,...,NaN,DMDA0A4M,7A1ADADA,0,4,11,1,119,FINFIN,0
16,2,52000,1,1616,19846,6,10.465116,0.000000,33798,3,...,NaN,3A2M3A3A,4ADA2ADA,0,0,10,0,175,FINFIN,1
17,2,52000,1,1616,19845,7,14.883721,8.888889,27212,35,...,NaN,DADA2ADA,DADA2ADA,0,2,9,0,280,FINFIN,1
18,2,52000,1,1616,19844,6,10.232558,4.444444,30805,52,...,NaN,7ADA0M0A,DM3A6M0A,0,6,3,1,79,FINFIN,0
19,2,52000,1,1616,19843,8,13.023256,6.666667,21903,22,...,NaN,7A5A7A2M,DA0A1A0A,0,3,5,0,260,FINFIN,0
20,2,52000,1,1616,19842,6,9.767442,6.666667,26006,12,...,NaN,7A5A7A2M,2A0M1A1A,0,3,6,0,260,FINFIN,0
21,1,52000,1,1616,19841,7,8.604651,2.222222,16302,8,...,NaN,DA7M7A7A,DA3ADA2A,0,5,9,1,162,FINFIN,0
22,1,52000,1,1616,19840,8,14.651163,2.222222,14001,82,...,NaN,DA7ADA7A,1ADA3ADA,0,4,11,0,126,FINFIN,0
23,1,52000,1,1616,19839,8,17.674419,0.000000,13997,60,...,NaN,5A3A4A0A,1ADA2ADA,0,1,4,0,79,FINFIN,0
24,1,52000,1,1616,19838,7,11.627907,0.000000,15805,60,...,NaN,1A2A0A1A,1A0A$0A1,0,0,9,0,5,FINFIN,0
25,1,52000,1,1616,19837,7,6.976744,2.222222,15748,7,...,NaN,2ADA0A3A,2ADA0A3A,0,0,9,0,377,FINFIN,0
26,1,52000,1,1616,19836,8,17.906977,0.000000,13770,136,...,NaN,AM6M6MDM,DMDA1M7M,0,0,6,0,24,FINFIN,0
27,1,52000,1,1616,19835,7,20.000000,2.222222,15684,104,...,NaN,DMDA7A3A,DA5A3ADA,0,3,4,0,93,FINFIN,0
28,1,52000,1,1616,19834,6,9.069767,2.222222,18243,3,...,NaN,4MDA7ADA,2A0ADM7M,0,5,5,1,47,FINFIN,0
29,1,52000,1,1616,19833,7,6.976744,0.000000,15418,199,...,NaN,DA7A7A2M,2ADA7A0A,0,3,5,0,107,FINFIN,0
30,1,52000,1,1616,19832,7,18.837209,2.222222,15404,369,...,NaN,6A0A7A0A,7A4A7A$D,0,23,6,0,147,FINFIN,0
31,1,38000,1,1617,19861,4,9.166667,0.000000,9482,4,...,NaN,2A7A4A7A,2A0A0M7A,0,0,2,0,51,FINFIN,0
32,1,38000,1,1617,19860,4,13.333333,0.000000,9272,7,...,NaN,1ADA7M6A,DADA0A6A,0,0,2,0,667,FINFIN,0
33,1,38000,1,1617,19859,4,10.833333,0.000000,9097,6,...,NaN,DM2M4ADM,7ADADA3A,0,1,1,0,77,FINFIN,0
34,1,38000,1,1617,19858,4,10.833333,0.000000,9040,34,...,NaN,DA1A0ADA,DADA0ADA,0,1,3,0,132,FINFIN,0
35,1,38000,1,1617,19857,4,9.166667,0.000000,8887,6,...,NaN,DA5A7A3M,DA0A1A0A,0,3,1,0,145,FINFIN,0
36,1,38000,1,1617,19856,4,20.000000,0.000000,8772,18,...,NaN,DADM4A5A,2ADMDM0A,0,12,2,0,272,FINFIN,0
37,1,38000,1,1617,19855,4,15.833333,0.000000,8357,7,...,NaN,4A1A7A3A,1A3A6A3A,0,1,1,0,107,FINFIN,0
38,1,38000,1,1617,19854,4,15.000000,0.000000,8345,34,...,NaN,7A5ADA7A,DA3ADA2A,0,12,1,0,73,FINFIN,1
39,1,38000,1,1617,19853,4,10.000000,0.000000,8080,8,...,NaN,DA4A$1A5,4ADADA3A,0,2,2,0,5,FINFIN,1
40,1,38000,1,1617,19852,4,9.166667,0.000000,7247,18,...,NaN,5A0A7A7A,5A0ADA5A,0,4,1,0,393,FINFIN,0
41,1,38000,1,1617,19851,4,12.500000,0.000000,5680,24,...,NaN,2A1A2ADA,3A7A7A2A,0,0,1,0,165,FINFIN,0
42,1,38000,1,1617,19850,4,10.000000,0.000000,4702,14,...,NaN,3M3ADA6M,1A2A7A7A,0,0,0,0,39,FINFIN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490263,1,24000,35,56524,699200,7,10.657895,0.000000,17360,12,...,2A6A0A$,7A0MDA0A,0A0A7A$1,0,5,7,0,107,FINFIN,0
490264,1,24000,35,56524,699201,7,12.236842,3.333333,17608,13,...,4A7A2A7A,4A0A3A0A,4A6A0AAA,0,2,8,0,89,FINFIN,0
490265,1,15000,35,56525,699202,4,20.000000,0.000000,20,16,...,$6A,3A0ADADA,DAAA5A0A,0,0,2,0,35,FINFIN,0
490266,1,15000,35,56525,699203,4,9.056604,0.000000,450,11,...,1A1A4ADA,3ADA2A5A,$7A4A2AD,0,0,3,0,8,FINFIN,0
490267,1,15000,35,56525,699204,4,8.679245,0.000000,455,3,...,3A,7A0MDA0A,0A0A7A$1,0,5,1,0,107,FINFIN,1
490268,1,15000,35,56525,699205,4,5.283019,0.000000,595,6,...,DADADADA,0,3A7A2A1A,0,0,1,0,0,FINFIN,1
490269,1,15000,35,56525,699206,4,3.773585,0.000000,750,51,...,2ADA$DA,0,0,0,0,0,0,0,FINFIN,0
490270,1,15000,35,56525,699207,4,9.056604,0.000000,815,71,...,7ARA$7A,$7A,$7A,0,0,0,0,1,FINFIN,0
490271,1,15000,35,56525,699208,4,10.188679,0.000000,1225,71,...,5A7ARADA,$0A0A0A5,$0A0A,0,0,0,0,5,FINFIN,0
490272,1,15000,35,56525,699209,4,5.660377,0.000000,1322,20,...,7A7A4A$,3A3A1ADA,1A3A0A$3,0,0,0,0,38,FINFIN,0
490273,1,15000,35,56525,699210,4,15.094340,0.000000,1372,7,...,7A3A2A0A,DA7A2M3M,DA4A7ADA,0,2,0,0,83,FINFIN,0
490274,1,15000,35,56525,699211,4,9.056604,0.000000,1400,12,...,0A7A$AA,0A6A3ADA,DM0A0A2A,0,2,1,0,68,FINFIN,0
490275,1,15000,35,56525,699212,4,1.886792,0.000000,1462,10,...,1ADA,6A2A3A1A,7A4ADA7A,0,1,1,0,141,FINFIN,0
490276,1,15000,35,56525,699213,4,6.415094,0.000000,1505,8,...,5A0A$0A,$7M0A0AD,$7M0A0A0,0,0,0,0,5,FINFIN,0
490277,1,15000,35,56525,699214,4,15.471698,0.000000,1605,16,...,7ADA3A$,7M7MDM5M,$4A1A7A6,0,24,0,0,69,FINFIN,0
490278,1,15000,35,56525,699215,4,16.226415,0.000000,1675,9,...,7M7M$7M,$2A4ADAD,0A7M0A2A,0,0,1,0,24,FINFIN,0
490279,1,5000,35,56526,699216,6,7.878788,0.000000,4308,22,...,7A6A7A7A,7A0A$4A7,$0A7A5A7,0,14,1,0,27,FINFIN,0
490280,1,5000,35,56526,699217,7,11.515152,0.000000,4570,10,...,2A7ARA2A,$7A7A2A3,$6A7A,0,2,2,0,39,FINFIN,0
490282,1,5000,35,56526,699219,6,20.000000,0.000000,5550,5,...,2A6A2A0A,2A7ADADA,DADA$2A3,0,0,6,0,30,FINFIN,1
490283,1,5000,35,56526,699220,6,18.787879,0.000000,5848,33,...,6M7A5A$,DM7A7A0M,$DA1A0A5,0,5,2,0,108,FINFIN,0
490284,1,5000,35,56526,699221,6,11.515152,0.000000,5953,5,...,5M2A7A3A,4A0A5ADA,1A0A6A0A,0,30,2,0,85,FINFIN,0
490285,1,5000,35,56526,699222,6,13.131313,0.000000,5960,15,...,DADA3ADA,$0ADA7A6,$0ADA7A6,0,0,1,0,9,FINFIN,0
490286,1,5000,35,56526,699223,6,18.989899,0.000000,6076,8,...,DA3ADA4A,$5A1ADA3,0,0,1,4,0,51,FINFIN,1
490287,2,5000,35,56526,699224,7,18.989899,0.000000,8022,41,...,4A7A4A7A,$0A1A7A3,$0A,0,1,2,0,6,FINFIN,0
490288,2,5000,35,56526,699225,7,19.393939,0.000000,8135,22,...,DA0A3A5A,$DM3M,$7A7A,0,1,2,0,2,FINFIN,0
490289,2,5000,35,56526,699226,7,14.949495,0.000000,8868,54,...,7A7A7A5A,0A7A$4A7,$7A0A,0,0,5,0,10,FINFIN,0
490290,2,5000,35,56526,699227,8,10.505051,0.000000,7802,5,...,3ADA0A7A,DA1ADADA,$1ADA7AD,0,1,6,0,282,FINFIN,0
490292,2,5000,35,56526,699229,8,14.545455,0.000000,8186,16,...,6A6A6A7A,7A1ADA7A,6A$0ADA7,0,1,5,0,8,FINFIN,0
490293,2,5000,35,56526,699230,6,10.505051,0.000000,11070,6,...,2A$7ADA,7A1ADA7A,$7ADA,0,1,2,0,8,FINFIN,0
490294,2,5000,35,56526,699231,7,18.585859,0.000000,9861,14,...,7A0A0A3A,4A0A5ADA,DA6ADA0A,0,30,4,0,85,FINFIN,0

In [129]:
if allure_etudier==1:
    df.to_csv('d:\diabolo_trans_trot.csv', header=False,index=False)
if allure_etudier==2:
    df.to_csv('d:\diabolo_trans_galop.csv', header=False,index=False)

KeyError: "['PAR_ARRIVEE'] not in index"